version: '3.3'

services: 
     ted:
       image: ted-search
       container_name: ted
       ports:
         - '8080:9191'


     revers_proxy:
         image: nginx:1.17.10
         depends_on: 
           - ted
         volumes: 
           - app/file_to_test_stage/nginx.conf:/etc/nginx/nginx.conf
           - ./app/target/classes/static:/etc/nginx/static
           
         ports: 
           - 80:80

# docker run -d -p 81:8080  --name=jeck -v jenkins-Data:/var/jenkins_home -v    j/var/run/docker.sock:/var/run/docker.sock jeck

volumes: 
     ngint.conf:
      